{% set name = "ofiber" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ofiber-{{ version }}.tar.gz
  sha256: cabd7bc2f6de5b7ded17d1f8ad1daeed1d9e797abf5ebb457e62d1d54fe32aa2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=44
  run:
    - pip
    - python >=3.7
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - ofiber
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scottprahl/ofiber
  summary: A python module for mode and power calculations for optical fibers.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://ofiber.readthedocs.io/
  dev_url: https://github.com/scottprahl/ofiber

extra:
  recipe-maintainers:
    - scottprahl
